name: Git Diff Action
on:
  push:
    branches:
      - master

jobs:
  diff:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Cache Git
      id: cache-git
      uses: actions/cache@v2
      with:
        path: /usr/bin/git
        key: ${{ runner.os }}-git-${{ hashFiles('**/.gitmodules') }}

    - name: Install Git if not cached
      run: |
        if [ ! -x "$(command -v git)" ]; then
          sudo apt-get update
          sudo apt-get install -y git
        fi

    - name: Use Cached Git
      run: |
        export PATH="/usr/bin/git:$PATH"
        git --version

    - name: Get commit hashes
      run: |
        git log --oneline
        git diff --name-only HEAD~1 HEAD
        #LAST_COMMIT=$(git rev-parse HEAD)
        #COMMIT_BEFORE_LAST=$(git rev-parse HEAD~1)
        #echo "::set-output name=last_commit::$LAST_COMMIT"
        #echo "::set-output name=commit_before_last::$COMMIT_BEFORE_LAST"

    - name: Create output directory
      run: mkdir diff_files

    - name: Get diff
      run: git diff --name-only ${{ steps.get_commit_hashes.outputs.commit_before_last }} ${{ steps.get_commit_hashes.outputs.last_commit }} > diff_files/files.txt

    - name: Show diff files
      run: cat diff_files/files.txt
