name: Git Diff Action
on:
  push:
    branches:
      - master

jobs:
  diff:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Cache Git
      id: cache-git
      uses: actions/cache@v2
      with:
        path: /usr/bin/git
        key: ${{ runner.os }}-git-${{ hashFiles('**/.gitmodules') }}

    - name: Install Git if not cached
      run: |
        if [ ! -x "$(command -v git)" ]; then
          sudo apt-get update
          sudo apt-get install -y git
        fi

    - name: Use Cached Git
      run: |
        export PATH="/usr/bin/git:$PATH"
        git --version

    - name: Get merge commit hash
      run: |
        echo "LAST_COMMIT=$(git log --merges -n 1 --pretty=format:%H)" >> $GITHUB_ENV
        echo "Value $LAST_COMMIT"
        #echo "COMMIT_BEFORE_LAST=$(git rev-list -n 1 --skip 1 echo $LAST_COMMIT)" >> $GITHUB_ENV
        echo "MY_VARIABLE=example" >> $GITHUB_ENV

    - name: Get the commit before the merge commit hash
      run: |
        echo "Value $LAST_COMMIT"
        echo "COMMIT_BEFORE_LAST=$(git rev-list -n 1 --skip 1 ${LAST_COMMIT})" >> $GITHUB_ENV
        echo "MY_VARIABLE=example" >> $GITHUB_ENV

    - name: Use Environment Variable
      run: |
        echo $LAST_COMMIT
        echo $COMMIT_BEFORE_LAST
        echo $MY_VARIABLE

    - name: Create output directory
      run: mkdir diff_files

    - name: Get diff
      run: |
        git diff --name-only ${{ env.commit_before_last }} ${{ env.last_commit }}
        git diff --name-only ${{ env.commit_before_last }} ${{ env.last_commit }} > diff_files/files.txt

    - name: Show diff files
      run: cat diff_files/files.txt
